-- Primeira migração de A Morada. Não apaga nem substitui tabelas existentes.
create table if not exists public.game_messages (
  id bigint generated by default as identity primary key,
  message_key text not null unique,
  message_text text not null,
  updated_at timestamptz not null default now()
);

alter table public.game_messages enable row level security;

create policy "Leitura pública das mensagens do jogo"
on public.game_messages for select
to anon
using (true);

create policy "Atualização pública temporária da mensagem do hub"
on public.game_messages for update
to anon
using (message_key = 'hub_message')
with check (message_key = 'hub_message');

insert into public.game_messages (message_key, message_text)
values ('hub_message', 'A cidade ainda se lembra de você.')
on conflict (message_key) do nothing;

