-- Segunda migração de A Morada: ficha e estado de Mannon.
-- Incremental: não apaga nem recria dados existentes.

create table if not exists public.character_state (
  id smallint primary key default 1 check (id = 1),
  character_name text not null default 'Mannon',
  current_health smallint not null default 6 check (current_health between 0 and 6),
  max_health smallint not null default 6 check (max_health = 6),
  current_sanity smallint not null default 20 check (current_sanity between 0 and 20),
  max_sanity smallint not null default 20 check (max_sanity = 20),
  films_remaining smallint not null default 13 check (films_remaining between 0 and 13),
  films_max smallint not null default 13 check (films_max = 13),
  current_location text not null default 'Entrada de Viksdal',
  updated_at timestamptz not null default now()
);

create table if not exists public.character_stats (
  id bigint generated by default as identity primary key,
  stat_key text not null unique,
  stat_name text not null,
  stat_value smallint not null,
  stat_type text not null check (stat_type in ('attribute', 'skill'))
);

create table if not exists public.character_conditions (
  id bigint generated by default as identity primary key,
  condition_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.character_state (id) values (1)
on conflict (id) do nothing;

insert into public.character_stats (stat_key, stat_name, stat_value, stat_type) values
  ('ver', 'VER', 3, 'attribute'),
  ('aguentar', 'AGUENTAR', 2, 'attribute'),
  ('lembrar', 'LEMBRAR', 2, 'attribute'),
  ('ceder', 'CEDER', 1, 'attribute'),
  ('criar', 'CRIAR', 4, 'attribute'),
  ('fugir', 'FUGIR', 2, 'attribute'),
  ('fotografia', 'Fotografia', 2, 'skill'),
  ('pintura', 'Pintura', 1, 'skill'),
  ('percepcao_detalhes', 'Percepção de detalhes', 1, 'skill'),
  ('memoria_afetiva', 'Memória afetiva', 1, 'skill'),
  ('esconder_se', 'Esconder-se', 1, 'skill')
on conflict (stat_key) do nothing;

alter table public.character_state enable row level security;
alter table public.character_stats enable row level security;
alter table public.character_conditions enable row level security;

grant select, update on public.character_state to anon;
grant select on public.character_stats to anon;
grant select, insert, update, delete on public.character_conditions to anon;
grant usage, select on all sequences in schema public to anon;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'character_state' and policyname = 'Leitura pública do estado de Mannon') then
    create policy "Leitura pública do estado de Mannon" on public.character_state for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'character_state' and policyname = 'Atualização pública temporária do estado de Mannon') then
    create policy "Atualização pública temporária do estado de Mannon" on public.character_state for update to anon using (id = 1) with check (id = 1);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'character_stats' and policyname = 'Leitura pública dos valores de Mannon') then
    create policy "Leitura pública dos valores de Mannon" on public.character_stats for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'character_conditions' and policyname = 'Leitura pública das condições') then
    create policy "Leitura pública das condições" on public.character_conditions for select to anon using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'character_conditions' and policyname = 'Controle público temporário das condições') then
    create policy "Controle público temporário das condições" on public.character_conditions for all to anon using (true) with check (true);
  end if;
end $$;

