-- Quarta migração de A Morada: galeria digital e Polaroids especiais.
-- Incremental: não apaga fotografias existentes.

create table if not exists public.digital_photos (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text not null default '',
  location text not null default '',
  photo_date date,
  is_favorite boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.special_polaroids (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  location text not null default '',
  time_record text not null check (time_record in ('PRESENTE', 'PASSADO', 'FUTURO')),
  ability_name text not null,
  ability_description text not null,
  ability_type text not null check (ability_type in ('PERMANENTE', '1X POR SESSÃO', 'CARGAS', 'USO ÚNICO')),
  max_uses smallint,
  remaining_uses smallint,
  is_revealed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.digital_photos enable row level security;
alter table public.special_polaroids enable row level security;

grant select, insert, update, delete on public.digital_photos to anon;
grant select, insert, update on public.special_polaroids to anon;
grant usage, select on all sequences in schema public to anon;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'digital_photos' and policyname = 'Galeria pública temporária') then
    create policy "Galeria pública temporária" on public.digital_photos for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'special_polaroids' and policyname = 'Polaroids públicas temporárias') then
    create policy "Polaroids públicas temporárias" on public.special_polaroids for all to anon using (true) with check (true);
  end if;
end $$;
