-- Sétima migração de A Morada: inventário e solicitações de ação.
-- Incremental: não altera nem remove dados dos sistemas anteriores.

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  image_url text not null default '',
  category text not null default 'OBJETO' check (category in ('OBJETO', 'CHAVE', 'CONSUMÍVEL', 'ARMA', 'REMÉDIO', 'OUTRO')),
  visible_description text not null default '' check (char_length(visible_description) <= 2000),
  examined_description text not null default '' check (char_length(examined_description) <= 2000),
  secret_description text not null default '' check (char_length(secret_description) <= 2000),
  master_notes text not null default '' check (char_length(master_notes) <= 2000),
  player_note text not null default '' check (char_length(player_note) <= 1000),
  quantity integer not null default 1 check (quantity between 0 and 9999),
  allows_multiple boolean not null default false,
  item_state text not null default 'NORMAL' check (item_state in ('NORMAL', 'DANIFICADO', 'VAZIO', 'INCOMPLETO', 'USADO')),
  is_examined boolean not null default false,
  is_visible boolean not null default false,
  is_favorite boolean not null default false,
  can_be_examined boolean not null default true,
  can_be_discarded boolean not null default false,
  can_player_change_quantity boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_items_single_quantity_check check (allows_multiple or quantity <= 1)
);

create table if not exists public.inventory_actions (
  id bigint generated by default as identity primary key,
  item_id bigint references public.inventory_items(id) on delete set null,
  item_name_snapshot text not null check (char_length(item_name_snapshot) between 1 and 120),
  action_type text not null check (action_type in ('USE', 'DISCARD', 'EXAMINE')),
  message text not null default '' check (char_length(message) <= 1000),
  status text not null default 'PENDING' check (status in ('PENDING', 'ACCEPTED', 'REJECTED')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint inventory_actions_resolution_check check (
    (status = 'PENDING' and resolved_at is null)
    or (status in ('ACCEPTED', 'REJECTED') and resolved_at is not null)
  )
);

create index if not exists inventory_items_visible_sort_idx
on public.inventory_items (is_visible, is_favorite desc, sort_order, id);

create index if not exists inventory_actions_item_id_idx
on public.inventory_actions (item_id);

create index if not exists inventory_actions_status_created_idx
on public.inventory_actions (status, created_at desc);

create unique index if not exists inventory_actions_one_pending_idx
on public.inventory_actions (item_id, action_type)
where status = 'PENDING' and item_id is not null;

create or replace view public.inventory_items_alice
with (security_invoker = true)
as
select
  id,
  name,
  image_url,
  category,
  visible_description,
  examined_description,
  player_note,
  quantity,
  allows_multiple,
  item_state,
  is_examined,
  is_favorite,
  can_be_examined,
  can_be_discarded,
  can_player_change_quantity,
  sort_order,
  created_at,
  updated_at
from public.inventory_items
where is_visible = true;

alter table public.inventory_items enable row level security;
alter table public.inventory_actions enable row level security;

revoke all on public.inventory_items from anon;
revoke all on public.inventory_actions from anon;
revoke all on public.inventory_items_alice from anon;
revoke all on sequence public.inventory_items_id_seq from anon;
revoke all on sequence public.inventory_actions_id_seq from anon;
revoke all on public.inventory_items from authenticated;
revoke all on public.inventory_actions from authenticated;
revoke all on public.inventory_items_alice from authenticated;
revoke all on sequence public.inventory_items_id_seq from authenticated;
revoke all on sequence public.inventory_actions_id_seq from authenticated;

grant select, insert, update, delete on public.inventory_items to anon;
grant select, insert, update on public.inventory_actions to anon;
grant select on public.inventory_items_alice to anon;
grant usage, select on sequence public.inventory_items_id_seq to anon;
grant usage, select on sequence public.inventory_actions_id_seq to anon;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_items'
      and policyname = 'Acesso temporário aos itens de inventário'
  ) then
    create policy "Acesso temporário aos itens de inventário"
    on public.inventory_items
    for all
    to anon
    using (id > 0)
    with check (id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_actions'
      and policyname = 'Leitura temporária das ações de inventário'
  ) then
    create policy "Leitura temporária das ações de inventário"
    on public.inventory_actions
    for select
    to anon
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_actions'
      and policyname = 'Criação temporária de ações de inventário'
  ) then
    create policy "Criação temporária de ações de inventário"
    on public.inventory_actions
    for insert
    to anon
    with check (status = 'PENDING' and resolved_at is null);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'inventory_actions'
      and policyname = 'Resolução temporária das ações de inventário'
  ) then
    create policy "Resolução temporária das ações de inventário"
    on public.inventory_actions
    for update
    to anon
    using (status = 'PENDING')
    with check (status in ('ACCEPTED', 'REJECTED') and resolved_at is not null);
  end if;
end
$$;
