-- Nona migração de A Morada: documentos, páginas e observações da Alice.
-- Incremental: não altera nem remove dados dos sistemas anteriores.

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 160),
  category text not null default 'OUTRO'
    check (category in ('CARTA', 'BILHETE', 'RELATÓRIO', 'DIÁRIO', 'RECORTE', 'REGISTRO', 'PÁGINA', 'FOTOGRAFIA', 'OUTRO')),
  found_location text not null default '' check (char_length(found_location) <= 160),
  document_date date,
  visible_summary text not null default '' check (char_length(visible_summary) <= 1200),
  master_notes text not null default '' check (char_length(master_notes) <= 3000),
  status text not null default 'OCULTO'
    check (status in ('OCULTO', 'REVELADO', 'INCOMPLETO', 'COMPLETO')),
  is_visible boolean not null default false,
  is_favorite boolean not null default false,
  sort_order integer not null default 0,
  alice_sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_pages (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  page_number integer not null check (page_number > 0),
  page_title text not null default '' check (char_length(page_title) <= 160),
  page_text text not null default '' check (char_length(page_text) <= 12000),
  image_url text not null default '' check (
    char_length(image_url) <= 2048
    and (image_url = '' or image_url ~ '^https?://')
  ),
  is_visible boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint document_pages_content_check check (
    char_length(trim(page_text)) > 0 or char_length(trim(image_url)) > 0
  ),
  constraint document_pages_document_number_key unique (document_id, page_number)
);

create table if not exists public.document_notes (
  id bigint generated by default as identity primary key,
  document_id bigint not null unique references public.documents(id) on delete cascade,
  note_text text not null default '' check (char_length(note_text) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists documents_visible_sort_idx
on public.documents (is_visible, is_favorite desc, alice_sort_order, sort_order, id);

create index if not exists document_pages_document_visible_sort_idx
on public.document_pages (document_id, is_visible, sort_order, page_number, id);

create or replace view public.documents_alice
with (security_invoker = true)
as
select
  id,
  title,
  category,
  found_location,
  document_date,
  visible_summary,
  status,
  is_favorite,
  sort_order,
  alice_sort_order,
  created_at,
  updated_at
from public.documents
where is_visible = true;

create or replace view public.document_pages_alice
with (security_invoker = true)
as
select
  page.id,
  page.document_id,
  page.page_number,
  page.page_title,
  page.page_text,
  page.image_url,
  page.sort_order,
  page.created_at,
  page.updated_at
from public.document_pages as page
join public.documents as document on document.id = page.document_id
where document.is_visible = true
  and page.is_visible = true;

create or replace view public.document_notes_alice
with (security_invoker = true)
as
select
  note.id,
  note.document_id,
  note.note_text,
  note.created_at,
  note.updated_at
from public.document_notes as note
join public.documents as document on document.id = note.document_id
where document.is_visible = true;

alter table public.documents enable row level security;
alter table public.document_pages enable row level security;
alter table public.document_notes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'documents'
      and policyname = 'Leitura temporária dos documentos'
  ) then
    create policy "Leitura temporária dos documentos"
    on public.documents for select to anon using (id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'documents'
      and policyname = 'Criação temporária dos documentos'
  ) then
    create policy "Criação temporária dos documentos"
    on public.documents for insert to anon
    with check (id > 0 and char_length(trim(title)) > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'documents'
      and policyname = 'Atualização temporária dos documentos'
  ) then
    create policy "Atualização temporária dos documentos"
    on public.documents for update to anon
    using (id > 0)
    with check (id > 0 and char_length(trim(title)) > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'documents'
      and policyname = 'Remoção temporária dos documentos'
  ) then
    create policy "Remoção temporária dos documentos"
    on public.documents for delete to anon using (id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'document_pages'
      and policyname = 'Leitura temporária das páginas'
  ) then
    create policy "Leitura temporária das páginas"
    on public.document_pages for select to anon using (id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'document_pages'
      and policyname = 'Criação temporária das páginas'
  ) then
    create policy "Criação temporária das páginas"
    on public.document_pages for insert to anon
    with check (
      id > 0 and document_id > 0
      and (char_length(trim(page_text)) > 0 or char_length(trim(image_url)) > 0)
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'document_pages'
      and policyname = 'Atualização temporária das páginas'
  ) then
    create policy "Atualização temporária das páginas"
    on public.document_pages for update to anon
    using (id > 0)
    with check (
      id > 0 and document_id > 0
      and (char_length(trim(page_text)) > 0 or char_length(trim(image_url)) > 0)
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'document_pages'
      and policyname = 'Remoção temporária das páginas'
  ) then
    create policy "Remoção temporária das páginas"
    on public.document_pages for delete to anon using (id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'document_notes'
      and policyname = 'Leitura temporária das observações'
  ) then
    create policy "Leitura temporária das observações"
    on public.document_notes for select to anon using (id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'document_notes'
      and policyname = 'Criação temporária das observações'
  ) then
    create policy "Criação temporária das observações"
    on public.document_notes for insert to anon
    with check (id > 0 and document_id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'document_notes'
      and policyname = 'Atualização temporária das observações'
  ) then
    create policy "Atualização temporária das observações"
    on public.document_notes for update to anon
    using (id > 0)
    with check (id > 0 and document_id > 0);
  end if;
end
$$;

-- Mantém as tabelas fechadas até a migração de permissões explícitas.
revoke all on public.documents from anon, authenticated;
revoke all on public.document_pages from anon, authenticated;
revoke all on public.document_notes from anon, authenticated;
revoke all on public.documents_alice from anon, authenticated;
revoke all on public.document_pages_alice from anon, authenticated;
revoke all on public.document_notes_alice from anon, authenticated;
revoke all on sequence public.documents_id_seq from anon, authenticated;
revoke all on sequence public.document_pages_id_seq from anon, authenticated;
revoke all on sequence public.document_notes_id_seq from anon, authenticated;
