-- Décima primeira migração de A Morada: caderno pessoal da Alice.
-- Incremental: não altera tabelas nem registros dos sistemas anteriores.

create table if not exists public.player_notes (
  id bigint generated by default as identity primary key,
  title text not null default '' check (char_length(title) <= 160),
  note_text text not null default '' check (char_length(note_text) <= 100000),
  category text not null default 'GERAL'
    check (category in ('GERAL', 'PESSOAS', 'LUGARES', 'SUSPEITAS', 'MEMÓRIAS', 'PENDÊNCIAS')),
  marker_style text not null default 'PÉROLA'
    check (marker_style in ('ROSA', 'OLIVA', 'PÉROLA', 'VINHO', 'CINZA', 'CREME')),
  is_favorite boolean not null default false,
  is_pinned boolean not null default false,
  is_archived boolean not null default false,
  sort_order integer not null default 0 check (sort_order between -1000000 and 1000000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists player_notes_archive_order_idx
on public.player_notes (is_archived, is_pinned desc, sort_order, updated_at desc, id);

create or replace function public.set_player_notes_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1 from pg_trigger
    where tgname = 'player_notes_set_updated_at'
      and tgrelid = 'public.player_notes'::regclass
  ) then
    create trigger player_notes_set_updated_at
    before update on public.player_notes
    for each row execute function public.set_player_notes_updated_at();
  end if;
end
$$;

alter table public.player_notes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'player_notes'
      and policyname = 'Leitura temporária das anotações pessoais'
  ) then
    create policy "Leitura temporária das anotações pessoais"
    on public.player_notes for select to anon
    using (id > 0);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'player_notes'
      and policyname = 'Criação temporária das anotações pessoais'
  ) then
    create policy "Criação temporária das anotações pessoais"
    on public.player_notes for insert to anon
    with check (
      id > 0
      and char_length(title) <= 160
      and char_length(note_text) <= 100000
      and category in ('GERAL', 'PESSOAS', 'LUGARES', 'SUSPEITAS', 'MEMÓRIAS', 'PENDÊNCIAS')
      and marker_style in ('ROSA', 'OLIVA', 'PÉROLA', 'VINHO', 'CINZA', 'CREME')
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'player_notes'
      and policyname = 'Atualização temporária das anotações pessoais'
  ) then
    create policy "Atualização temporária das anotações pessoais"
    on public.player_notes for update to anon
    using (id > 0)
    with check (
      id > 0
      and char_length(title) <= 160
      and char_length(note_text) <= 100000
      and category in ('GERAL', 'PESSOAS', 'LUGARES', 'SUSPEITAS', 'MEMÓRIAS', 'PENDÊNCIAS')
      and marker_style in ('ROSA', 'OLIVA', 'PÉROLA', 'VINHO', 'CINZA', 'CREME')
    );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'player_notes'
      and policyname = 'Remoção temporária das anotações pessoais'
  ) then
    create policy "Remoção temporária das anotações pessoais"
    on public.player_notes for delete to anon
    using (id > 0);
  end if;
end
$$;

-- O gatilho é usado internamente pelo banco e não deve virar uma RPC pública.
revoke execute on function public.set_player_notes_updated_at() from public, anon, authenticated;

-- Mantém a tabela fechada até a migração de privilégios explícitos.
revoke all on public.player_notes from public, anon, authenticated;
revoke all on sequence public.player_notes_id_seq from public, anon, authenticated;
